[Server]
Mode = "debug"
Addr = "0.0.0.0:8888"
ReadTimeout = 60
WriteTimeout = 60

[Database]
Dialect = "mysql"
User = "root"
Password = "root"
Host = "localhost:3306"
Name = "blog"
Protocol = "tcp"
Charset = "utf8"
ParseTime = "True"
Loc = "Local"
MaxIdleConns = 10
MaxOpenConns = 100
TablePrefix = "blog_"
